### PR TITLE
Export Fetch API

### LINKED ISSUE #438: Consider relax zod-checking of service bindings?
In `@miniflare/tre`, we're using Zod to check the types of any service bindings functions. Unless we resolve to the same undici version, `@miniflare/tre` gets its own, and our custom service binding will fail at these checks.

Either `@miniflare/tre` should export Fetch API things (e.g. `Request` and `Response`), or we should consider relaxing the Zod checking. Using Node's new built-ins seems to work just fine, so maybe these checks are actually not really necessary at all?

### PR DESCRIPTION
**Pull request by GregBrimble**
Fixes #438

### CODE REVIEW

File: packages/tre/src/index.ts [hunk 1]
```diff
@@ -614,3 +617,4 @@ export * from "./plugins";
 export * from "./runtime";
 export * from "./shared";
 export * from "./storage";
+export { FormData, File, Headers, Request, Response, fetch };
```
Comment (mrbbot) [inline packages/tre/src/index.ts:620]: Might be useful to export the types here too, just so you can do `import { Headers, HeadersInit } from "..."` without having to `import ... from "undici"` too?

**Review by mrbbot — APPROVED** [review]
